PoliticalApp/PoliticalAppUI/Controllers/EventsVolunteersAppointmentsController.cs
using PoliticalAppRepository;
using Server.PoliticalAppDataEntities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using PagedList;
using PoliticalAppUI.Models;

namespace PoliticalAppUI.Controllers
{
    public class EventsVolunteersAppointmentsController : BaseController
    {

        #region Private Members

        private IActivitiesRepository _ActRepository;

        #endregion

        #region Constructor
        public EventsVolunteersAppointmentsController(IActivitiesRepository ActRepository)
        {
            _ActRepository = ActRepository;
        }
        #endregion

        #region Action Methods

        // GET: EventsVolunteersAppointments
        public ActionResult Index(int page = 1)
        {
            EventsModel _eventsModel = new EventsModel();
            // I do this just in case someone tries to put in 0 or a negative number
            if (page < 1)
            {
                page = 1;
            }
             _eventsModel.eventsList = _ActRepository.GetEvents().ToPagedList(page, 5);


             return View(_eventsModel);
        }

       [System.Web.Mvc.HttpPost]
        public ActionResult Index(Event events)
        {
            events.EventBeginDate = DateTime.UtcNow;
            events.EventEndDate = DateTime.UtcNow;
            events.AddedOn = DateTime.UtcNow;
            events.UpdatedOn = DateTime.UtcNow;
            events.PoliticalPartyID = _ActRepository.GetPartyInformation().PoliticalPartyID;
            Politician pol = (Politician)Session["User"];

            events.PoliticianID = pol.PoliticianID;
            var id = _ActRepository.InsertEvent(events);

            return RedirectToAction("Index");
        }

       public ActionResult Volunteers(int page = 1, int page1 = 1)
        {
            // I do this just in case someone tries to put in 0 or a negative number
            if (page < 1)
            {
                page = 1;
            }

            if (page1 < 1)
            {
                page1 = 1;


            }

            VolunteerModel volunteers = new VolunteerModel();

            int pageSize = 5;

            //Used the following two formulas so that it doesn't round down on the returned integer
            decimal VolunteerListTotalPages = ((decimal)(_ActRepository.VolunteersList().Count() / (decimal)pageSize));
            decimal VolunterRequestTotalPages = ((decimal)(_ActRepository.VolunteerRequestList().Count() / (decimal)pageSize));

            volunteers.VolunteersList = _ActRepository.VolunteersList().ToPagedList(page, pageSize);
            volunteers.VolunteerRequestList = _ActRepository.VolunteerRequestList().ToPagedList(page1, pageSize);

            ViewBag.VolunteerListTotalPages = Math.Ceiling(VolunteerListTotalPages);
            ViewBag.VolunteerRequestTotalPages = Math.Ceiling(VolunterRequestTotalPages);

            ViewBag.PageNumberAudio = page;
            ViewBag.PageNumberVideo = page1;

            if (page > 1)
                return Request.IsAjaxRequest() ? (ActionResult)PartialView("VolunteerPartialList", volunteers) : View(volunteers);
            else
                return Request.IsAjaxRequest() ? (ActionResult)PartialView("VolunteerPartialRequest", volunteers) : View(volunteers);

        }

        public ActionResult Appointments(int page = 1, int page1 = 1)
        {
            // I do this just in case someone tries to put in 0 or a negative number
            if (page < 1)
            {
                page = 1;
            }

            if (page1 < 1)
            {
                page1 = 1;
            }

            AppointmentsModel Appointments = new AppointmentsModel();

            int pageSize = 5;

            //Used the following two formulas so that it doesn't round down on the returned integer
            decimal AppointmentsTotalPages = ((decimal)(_ActRepository.AppointmentList().Count() / (decimal)pageSize));
            decimal PendingAppointmentsTotalPages = ((decimal)(_ActRepository.PendingAppointmentList().Count() / (decimal)pageSize));

            Appointments.appointmentList = _ActRepository.AppointmentList().ToPagedList(page, pageSize);
            Appointments.pendingAppointmentList = _ActRepository.PendingAppointmentList().ToPagedList(page1, pageSize);

            ViewBag.AppointmentsTotalPages = Math.Ceiling(AppointmentsTotalPages);
            ViewBag.PendingAppointmentsTotalPages = Math.Ceiling(PendingAppointmentsTotalPages);

            ViewBag.PageNumberAudio = page;
            ViewBag.PageNumberVideo = page1;

            if (page > 1)
                return Request.IsAjaxRequest() ? (ActionResult)PartialView("AppointmentsPartial", Appointments) : View(Appointments);
            else
                return Request.IsAjaxRequest() ? (ActionResult)PartialView("PendingAppointmentsPartial", Appointments) : View(Appointments);

        }
        #endregion
    }
}

PoliticalApp/PoliticalAppUI/Views/EventsVolunteersAppointments/Appointments.cshtml
@model AppointmentsModel

@{
    ViewBag.Title = "Appointments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using PoliticalAppUI.Models;
@using Server.PoliticalAppDataEntities;
@using PagedList.Mvc;
@using PagedList;

<h2>Appointments</h2>

<div class="container">
    <div class="wrapper">
        <h2><i class="fa fa-calendar"></i> Appointments<span class="right-sitemap">Your are here: <a href="index.html">Dashboard</a> <i class="fa fa-chevron-right"></i> <span>Appointments</span></span></h2>
        <section class="topmargin10 section-col section-fw">


            <div>

                
                
                <div id="tab-container" class='tab-container'>
                    <ul class='etabs'>
                        <li class='tab'><a href="#tabs1-Audio">Appointments</a></li>
                        <li class='tab'><a href="#tabs1-Video">Pending Appointments</a></li>
                    </ul>
                    <div class="gr-action">
                        <button class="btn-red">Delete</button>
                    </div>
                    <div class="clr"></div>
                    <div class='panel-container'>

                        @Html.Partial("AppointmentsPartial", Model)
                        @Html.Partial("PendingAppointmentsPartial", Model)

                   

                    </div>
                </div>
            </div>
        </section>

        <div class="clr"></div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $('#tab-container').easytabs();
    });

   

    function ChangeUrl(page, url) {
        if (typeof (history.pushState) != "undefined") {
            var obj = { Page: page, Url: url };
            history.pushState(obj, obj.Page, obj.Url);
        } else {
            alert("Browser does not support HTML5.");
        }
    }


    $(function () {

        $('body').on('click', '#tabs1-Audio .pagination a', function (event) {
            event.preventDefault();
            console.log('page');


            var url = $(this).attr('href');
            console.log(url);
            $.ajax({
                url: url,
                success: function (result) {
                    ChangeUrl('index', url);
                    $('#tabs1-Audio').html(result);
                }
            });
        });

        $('body').on('click', '#tabs1-Video .pagination a', function (event) {
            event.preventDefault();
            console.log('page');

            var url = $(this).attr('href');

            console.log(url);
            $.ajax({
                url: url,
                success: function (result) {
                    ChangeUrl('index', url);
                    $('#tabs1-Video').html(result);
                }
            });
        });
    });

</script>

PoliticalApp/PoliticalAppUI/Views/EventsVolunteersAppointments/AppointmentsPartial.cshtml
@model AppointmentsModel

@using PoliticalAppUI.Models;
@using Server.PoliticalAppDataEntities;
@using PagedList.Mvc;
@using PagedList;

<div id="tabs1-Audio">
    <div class="grid-container">
        <ul class="gr-header">
            <li><input type="checkbox"></li>
            <li class="name"><i class="fa fa-user"></i> Name</li>
            <li class="place"><i class="fa fa-file-text-o"></i> Subject</li>
            <li class="date"><i class="fa fa-calendar"></i> Date &amp; Time</li>
            <li class="play"><i class="fa fa-pencil-square-o"></i> Reschedule</li>
        </ul>
        
        @foreach (Appointment p in Model.appointmentList)
        {
            <ul class="gr-content-row">
                <li><input type="checkbox"></li>
                <li class="name"> @p.CitizenID</li>
                <li class="place">@p.Message</li>
                <li class="date">@p.AppointmentDate</li>
                <li class="play">
                    <button>Reschedule</button>
                </li>
            </ul>
        }

        <ul class="gr-content-row">
            <li> Page @ViewBag.PageNumberAudio of @ViewBag.AppointmentsTotalPages  </li>
        </ul>

        <div class="clr"></div>
        <div class="pager-container">
            <ul>
                @Html.PagedListPager(Model.appointmentList, page => Url.Action("Appointments", new { page }), new PagedList.Mvc.PagedListRenderOptions { DelimiterBetweenPageNumbers = "|", MaximumPageNumbersToDisplay = 5 })

            </ul>
        </div>
    </div>

</div>

PoliticalApp/PoliticalAppUI/Views/EventsVolunteersAppointments/Index.cshtml
@*@model IEnumerable<Server.PoliticalAppDataEntities.Event>*@

@model  EventsModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using PoliticalAppUI.Models;
@using PagedList.Mvc;
@using PagedList;

<h2>Events</h2>

<div class="container">
    <div class="wrapper">
        <h2><span class="header-icon"><img src="images/icon-speech.png" width="19" height="21" alt="" /></span> Events<span class="right-sitemap">Your are here: <a href="index.html">Dashboard</a> <i class="fa fa-chevron-right"></i> <span>Events</span></span></h2>
        <section class="topmargin10 section-col">


            <div>

                <div id="tab-container" class='tab-container'>
                    <ul class='etabs'>
                        <li class='tab'><a href="#tabs1-Audio">Upcoming Events</a></li>
                    </ul>
                    <div class="gr-action">
                        <button>Edit</button>
                        <button class="btn-red">Delete</button>
                    </div>
                    <div class="clr"></div>
                    <div class='panel-container'>
                        <div id="tabs1-Audio">
                            @if (Model.eventsList != null)
                            {

                                <div class="grid-container events-gr">
                                    <ul class="gr-header">
                                        <li><input type="checkbox"></li>
                                        <li class="name"><i class="fa fa-user"></i> Name</li>
                                        <li class="place"><i class="fa fa-map-marker"></i> Place</li>
                                        <li class="date"><i class="fa fa-calendar"></i> Date</li>
                                    </ul>
                                    @foreach (var item in Model.eventsList)
                                    {
                                    <ul class="gr-content-row">
                                        <li><input type="checkbox"></li>
                                        <li class="name">@item.EventName</li>
                                        <li class="place">@item.EventLocation</li>
                                        <li class="date">@item.EventBeginDate</li>
                                    </ul>
                                    }

                                    <div class="clr"></div>
                                    <div class="pager-container">
                                        <ul>
                                            @Html.PagedListPager(Model.eventsList, page => Url.Action("Index", new { page }))
                                        </ul>
                                    </div>
                                </div>

                            }
                        </div>



                    </div>
                </div>
            </div>
        </section>
        <section class="topmargin10 section-col form-section">
            <div class="section-header">
                <h3>Add Events</h3>
                <div class="clr"></div>
            </div>

            @using (Html.BeginForm("Index", "EventsVolunteersAppointments", FormMethod.Post, Model.events))
            {


                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)


                <div class="fancy_fields form-container">
                    @Html.TextBoxFor(m => m.events.EventName, new { placeholder = "EventName" })
                    @*<input type="text" name="title" placeholder="Title">*@
                    <div class="col-half">
                        @Html.TextBoxFor(m => m.events.EventBeginDate, new { placeholder = "EventBeginDate" })
                        @*<input type="text" name="date" placeholder="dd/mm/yyy">*@
                    </div>
                    <div class="col-half">
                        @Html.TextBoxFor(m => m.events.EventEndDate, new { placeholder = "EventEndDate" })
                        @*<input type="text" name="time" placeholder="00:00">*@
                    </div>
                    <div class="clr"></div>
                    @Html.TextBoxFor(m => m.events.EventLocation, new { placeholder = "EventLocation" })
                    @*<input type="text" name="place" placeholder="Place">*@

                    @Html.TextBoxFor(m => m.events.Agenda, new { placeholder = "Agenda" })

                    @Html.TextAreaFor(m => m.events.Description, new { placeholder = "Description" })

                    <div class="topmargin30">
                        <button class="btn-white">Clear</button>
                        <button class="marginleft20" type="submit" value="Create">Submit</button>
                    </div>
                </div>
            }
        </section>
        <div class="clr"></div>
    </div>
</div>

PoliticalApp/PoliticalAppUI/Views/EventsVolunteersAppointments/PendingAppointmentsPartial.cshtml
@model AppointmentsModel

@using PoliticalAppUI.Models;
@using Server.PoliticalAppDataEntities;
@using PagedList.Mvc;
@using PagedList;



<div id="tabs1-Video">
    <div class="grid-container">
        <ul class="gr-header">
            <li><input type="checkbox"></li>
            <li class="name"><i class="fa fa-user"></i> Name</li>
            <li class="place"><i class="fa fa-file-text-o"></i> Subject</li>
            <li class="date"><i class="fa fa-calendar"></i> Date</li>
            <li class="play"><i class="fa fa-check"></i> Approve</li>
        </ul>

        @foreach (Appointment p in Model.appointmentList)
        {
            <ul class="gr-content-row">
                <li><input type="checkbox"></li>
                <li class="name"> @p.CitizenID</li>
                <li class="place">@p.Message</li>
                <li class="date">@p.AppointmentDate</li>
                <li class="play">
                    <button>Approve</button>
                </li>
            </ul>
        }

        <ul class="gr-content-row">
            <li> Page @ViewBag.PageNumberVideo of @ViewBag.PendingAppointmentsTotalPages  </li>
        </ul>       

        <div class="clr"></div>
        <div class="pager-container">
            <ul>
                @Html.PagedListPager(Model.pendingAppointmentList, page => Url.Action("Appointments", new { Page1 = page }), new PagedList.Mvc.PagedListRenderOptions { DelimiterBetweenPageNumbers = "|", MaximumPageNumbersToDisplay = 5 })

            </ul>
        </div>
    </div>
    <div class="clr"></div>
</div>

PoliticalApp/PoliticalAppUI/Views/EventsVolunteersAppointments/VolunteerPartialList.cshtml
@model VolunteerModel


@using PoliticalAppUI.Models;
@using Server.PoliticalAppDataEntities;
@using PagedList.Mvc;
@using PagedList;

<div id="tabs1-Audio">
    <div class="grid-container gr-volunteers">
        <ul class="gr-header">
            <li><input type="checkbox"></li>
            <li class="name"><i class="fa fa-user"></i> Name</li>
            <li class="place"><i class="fa fa-map-marker"></i> Location</li>
            <li class="email"><i class="fa fa-envelope"></i> Email</li>
            <li class="phone"><i class="fa fa-phone"></i> Phone</li>
            <li class="taskassign"><i class="fa fa-tasks"></i> Assign a Task</li>
        </ul>





        @foreach (Volunteer p in Model.VolunteersList)
        {
            <ul class="gr-content-row">
                <li><input type="checkbox"></li>
                <li class="name">Jennifer @p.CitizenID</li>
                <li class="place">Hyderabad @p.EventID</li>
                <li class="email">mail.Jennifer@gmail.com</li>
                <li class="phone">012345678</li>
                <li class="taskassign"><button>Assign a task</button></li>
            </ul>
        }

        <ul class="gr-content-row">
            <li> Page @ViewBag.PageNumberAudio of @ViewBag.VolunteerListTotalPages  </li>
        </ul>

        <div class="clr"></div>
        <div class="pager-container">
            <ul>
                @Html.PagedListPager(Model.VolunteersList, page => Url.Action("Volunteers", new { page }), new PagedList.Mvc.PagedListRenderOptions { DelimiterBetweenPageNumbers = "|", MaximumPageNumbersToDisplay = 5 })

            </ul>
        </div>
    </div>

</div>

PoliticalApp/PoliticalAppUI/Views/EventsVolunteersAppointments/VolunteerPartialRequest.cshtml
@model VolunteerModel

@using PoliticalAppUI.Models;
@using Server.PoliticalAppDataEntities;
@using PagedList.Mvc;
@using PagedList;

<div id="tabs1-Video">
    <div class="grid-container gr-volunteers">



        <ul class="gr-header">
            <li><input type="checkbox"></li>
            <li class="name"><i class="fa fa-user"></i> Name</li>
            <li class="place"><i class="fa fa-map-marker"></i> Location</li>
            <li class="email"><i class="fa fa-envelope"></i> Email</li>
            <li class="phone"><i class="fa fa-phone"></i> Phone</li>
            <li class="taskassign"><i class="fa fa-tasks"></i> Assign a Task</li>
        </ul>


        @foreach (Volunteer p in Model.VolunteerRequestList)
        {




            <ul class="gr-content-row">
                <li><input type="checkbox"></li>
                <li class="name">Jennifer @p.CitizenID</li>
                <li class="place">Hyderabad @p.EventID</li>
                <li class="email">mail.Jennifer@gmail.com</li>
                <li class="phone">012345678</li>
                <li class="taskassign"><button>Assign a task</button></li>
            </ul>

        }

        <ul class="gr-content-row">
            <li> Page @ViewBag.PageNumberVideo of @ViewBag.VolunteerRequestTotalPages  </li>
        </ul>

        <div class="clr"></div>
        <div class="pager-container">
            <ul>
                @Html.PagedListPager(Model.VolunteerRequestList, page => Url.Action("Volunteers", new { Page1 = page }), new PagedList.Mvc.PagedListRenderOptions { DelimiterBetweenPageNumbers = "|", MaximumPageNumbersToDisplay = 5 })

            </ul>
        </div>
    </div>

</div>

PoliticalApp/PoliticalAppUI/Views/EventsVolunteersAppointments/Volunteers.cshtml
@model VolunteerModel

@{
    ViewBag.Title = "Volunteers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using PoliticalAppUI.Models;
@using Server.PoliticalAppDataEntities;
@using PagedList.Mvc;
@using PagedList;




<h2>Volunteers</h2>


<div class="container">
    <div class="wrapper">
        <h2><i class="fa fa-comments"></i> Volunteers<span class="right-sitemap">Your are here: <a href="index.html">Dashboard</a> <i class="fa fa-chevron-right"></i> <span>Volunteers</span></span></h2>
        <section class="topmargin10 section-col section-fw">
            <div>



                <div id="tab-container" class='tab-container'>
                    <ul class='etabs'>
                        <li class='tab'><a href="#tabs1-Audio">Volunteers</a></li>
                        <li class='tab'><a href="#tabs1-Video">Volunteer Request</a></li>
                    </ul>
                    <div class="gr-action">
                        <button class="btn-red">Delete</button>
                    </div>
                    <div class="clr"></div>
                    <div class='panel-container'>

                        @Html.Partial("VolunteerPartialList", Model)
                        @Html.Partial("VolunteerPartialRequest", Model)



                    </div>
                </div>
            </div>
        </section>

        <div class="clr"></div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#tab-container').easytabs();
    });



    function ChangeUrl(page, url) {
        if (typeof (history.pushState) != "undefined") {
            var obj = { Page: page, Url: url };
            history.pushState(obj, obj.Page, obj.Url);
        } else {
            alert("Browser does not support HTML5.");
        }
    }


    $(function () {

        $('body').on('click', '#tabs1-Audio .pagination a', function (event) {
            event.preventDefault();
            console.log('page');


            var url = $(this).attr('href');
            console.log(url);
            $.ajax({
                url: url,
                success: function (result) {
                    ChangeUrl('index', url);
                    $('#tabs1-Audio').html(result);
                }
            });
        });

        $('body').on('click', '#tabs1-Video .pagination a', function (event) {
            event.preventDefault();
            console.log('page');

            var url = $(this).attr('href');

            console.log(url);
            $.ajax({
                url: url,
                success: function (result) {
                    ChangeUrl('index', url);
                    $('#tabs1-Video').html(result);
                }
            });
        });
    });

</script>