PoliticalApp/PoliticalAppUI/Controllers/CitizenController.cs
using PoliticalAppRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace PoliticalAppUI.Controllers
{
    public class CitizenController : BaseController
    {

        #region Private Members

        private ICitizenRepository _citizenRepository;

        private const int PageSize = 5;
        private const int FirstPageIndex = 1;
        private int? _fullCategoryCount;

        #endregion

        public CitizenController(ICitizenRepository citizenRepository)
        {
            _citizenRepository = citizenRepository;
        }

        #region Public Properties

        public int FullCategoryCount
        {
            get
            {
                if (_fullCategoryCount == null)
                {
                    _fullCategoryCount = _citizenRepository.GetCitizensCount();
                }

                return (int)_fullCategoryCount;
            }
        }

        #endregion

        #region Action Methods

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Dashboard()
        {
            return View();
        }

        

       

        #endregion

        #region Private Methods

       

        #endregion


    }
}

PoliticalApp/PoliticalAppUI/Controllers/ComplaintsFeedbackController.cs
using PoliticalAppRepository;
using PoliticalAppUI.Models;
using Server.PoliticalAppDataEntities;
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.IO;
using PagedList;
namespace PoliticalAppUI.Controllers
{
    public class ComplaintsFeedbackController : BaseController
    {

        #region private member
        private IActivitiesRepository _ActRepository;
        #endregion

        #region Constructor
        public ComplaintsFeedbackController(IActivitiesRepository ActRepository)
        {
            _ActRepository = ActRepository;
        }
        #endregion

        #region ActionMethods

        //public ActionResult Index(int page = 1, int sortBy = 1, bool isAsc = true, string search = null)
        //{
        //    List<Complaint> Complaint = new List<Complaint>();
        //    const int pageSize = 5;
        //    var totalRows = _ActRepository.GetComplaintsCount();

        //    Complaint = _ActRepository.GetComplaintsPage(page, pageSize, "citizenId", true);


        //    var data = new PagedCustomerModel()
        //    {
        //        TotalRows = totalRows,
        //        PageSize = pageSize,
        //        Complaint = Complaint
        //    };
        //    return View(data);
        //}

        public ActionResult Index(int page = 1, int page1 = 1)
        {
            // I do this just in case someone tries to put in 0 or a negative number
            if (page < 1)
            {
                page = 1;
            }

            if (page1 < 1)
            {
                page1 = 1;
            }

            ComplaintsFeedBackModel CompliantFeedBacks = new ComplaintsFeedBackModel();

            int pageSize = 5;

            //Used the following two formulas so that it doesn't round down on the returned integer
            decimal ComplainttotalPages = ((decimal)(_ActRepository.GetComplaints().Count() / (decimal)pageSize));
            decimal FeedBacktotalPages = ((decimal)(_ActRepository.GeFeedBacks().Count() / (decimal)pageSize));

            CompliantFeedBacks.ComplaintList = _ActRepository.GetComplaints().ToPagedList(page, pageSize);
            CompliantFeedBacks.FeedBackList = _ActRepository.GeFeedBacks().ToPagedList(page1, pageSize);

            ViewBag.ComplainttotalPages = Math.Ceiling(ComplainttotalPages);
            ViewBag.FeedBacktotalPages = Math.Ceiling(FeedBacktotalPages);

            ViewBag.pageNumberComplaint = page;
            ViewBag.PageNumberFeedBack = page1;
            if (page > 1)
                return Request.IsAjaxRequest() ? (ActionResult)PartialView("ComplaintsPartialList", CompliantFeedBacks) : View(CompliantFeedBacks);
            else
                return Request.IsAjaxRequest() ? (ActionResult)PartialView("FeedbackPartialList", CompliantFeedBacks) : View(CompliantFeedBacks);

        }
        public ActionResult Feedback()
        {
            return View();
        }

       
        #endregion



    }
}

PoliticalApp/PoliticalAppUI/Controllers/ConferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PoliticalAppUI.Controllers
{
    public class ConferenceController : Controller
    {
        //
        // GET: /Conference/

        public ActionResult Index()
        {
            return View();
        }

    }
}

PoliticalApp/PoliticalAppUI/Controllers/SettingsProfilesController.cs
using PoliticalAppRepository;
using Server.PoliticalAppDataEntities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using PagedList;
using PoliticalAppUI.Models;
namespace PoliticalAppUI.Controllers
{
    public class SettingsProfilesController : BaseController
    {
        //
        // GET: /SettingsProfiles/

        #region Private Members

        private IActivitiesRepository _ActRepository;

        #endregion

        #region Constructor
        public SettingsProfilesController(IActivitiesRepository ActRepository)
        {
            _ActRepository = ActRepository;
        }
        #endregion

        public ActionResult Index(int page = 1)
        {
            PartyworkerModel _partyWorkerModel = new PartyworkerModel();
            // I do this just in case someone tries to put in 0 or a negative number
            if (page < 1)
            {
                page = 1;
            }
            _partyWorkerModel.PartyWorkersList = _ActRepository.GetPartyWorkers().ToPagedList(page, 5);
            return View(_partyWorkerModel);
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult Index(PartyWorker partyWorker)
        {
            partyWorker.CitizenID = 5;

            partyWorker.PoliticianID = _ActRepository.GetPartyInformation().PoliticalPartyID;

            Politician pol = (Politician)Session["User"];
            partyWorker.PoliticianID = pol.PoliticianID;
            var id = _ActRepository.InsertPartyWorker(partyWorker);

            return RedirectToAction("Index");
        }

        public ActionResult Profiles()
        {
            return View();
        }

    }
}

PoliticalApp/PoliticalAppUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Political App CMS</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    

    <link type="text/css" href="/Content/PagedList.css" rel="stylesheet" />  


    <link type="text/css" rel="stylesheet" href="/Content/style.css">
    <link type="text/css" rel="stylesheet" href="/Content/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,400italic,600italic,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <script src="/Scripts/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="/Scripts/script.js"></script>
    <script src="/Scripts/jquery.hashchange.min.js" type="text/javascript"></script>
    <script src="/Scripts/jquery.easytabs.min.js" type="text/javascript"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    @*<script src="/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>*@

</head>


<body>
    <div id="menu-toggle">
        <img src="/Images/menu.png" width=20 height=20 alt="Menu" class="toggle-on" />
        <img src="/Images/current-arrow.png" alt="Menu" class="toggle-off" />
        <span>Menu</span>
    </div>

    <nav id="menu">

        <a href='@Url.Action(    "Dashboard",       "Citizen")                   ' class="dashboard current">Dashboard</a>
        <a href='@Url.Action(    "Index",          "Citizen")                   ' class="flag">Citizen Data</a>
        <a href='@Url.Action(    "Index",         "SpeechesGallery")                   ' class="speech">Speeches</a>
        <a href='@Url.Action(    "Index",         "ComplaintsFeedback")                ' class="complaints">Complaint &amp; Feedbacks</a>
        <a href='@Url.Action(    "Appointments",  "EventsVolunteersAppointments")      ' class="appointments">Appointments</a>
        <a href='@Url.Action("Index",                    "Conference")                           ' class="conference">Conference</a>
        <a href='@Url.Action(    "Volunteers",    "EventsVolunteersAppointments")      ' class="volunteers">Manage Volunteers</a>
        <a href='@Url.Action(    "Index",         "EventsVolunteersAppointments")      ' class="events">Events</a>
        <a href='@Url.Action(    "Gallery",       "SpeechesGallery")                   ' class="gallery">Gallery</a>
        <a href='@Url.Action(    "Profiles",        "SettingsProfiles")                   ' class="user">Profile Updates</a>
        <a href='@Url.Action(    "Index",           "SettingsProfiles")                   ' class="user">Settings</a>


    </nav>

    <header class="topheader">
        <a href="index.html"><img src="~/Images/logo.png" alt="party-logo" /></a>
        <div class="headerlinks"><i class="fa fa-user"></i><a href="#">@ViewBag.UserName !</a> | <a href='@Url.Action("Index", "Login")'>Logout</a></div>
    </header>
    <div class="container">

        <div class="wrapper dashboard">
            @RenderBody()

        </div>
    </div>
    <footer>&#169; 2015. All rights reseved by <a href="http://www.ascendiatech.in" target="_blank"> ascendiatech.in</a></footer>
</body>

</html>

PoliticalApp/PoliticalAppUI/Views/Shared/_LayoutPageLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Political App CMS</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <link type="text/css" rel="stylesheet" href="/Content/style.css">
    <link type="text/css" rel="stylesheet" href="/Content/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,400italic,600italic,700italic,900,900italic' rel='stylesheet' type='text/css'>

   

</head>


<body>
   
    <div style="padding-left:350px">
        <div class="wrapper dashboard">
            @RenderBody()

        </div>
    </div>
    
</body>

</html>